✨feat(#390): complete admin elastic search api endpoint in swagger

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 # Check if nvm is installed
-command -v nvm >/dev/null 2>&1 || { echo >&2 "nvm is required, but it's not installed.  Aborting."; exit 1; }
+if [ ! -d "$HOME/.nvm" ]; then echo >&2 "nvm is required, but it's not installed. Aborting."; exit 1; fi
+# command -v nvm >/dev/null 2>&1 || { echo >&2 "nvm is required, but it's not installed. Aborting."; exit 1; }
 
 # Make NVM available for script use
 export NVM_DIR=$HOME/.nvm;
@@ -11,7 +12,7 @@ source $NVM_DIR/nvm.sh;
 args=$1
 
 if [ "$args" == "re-install" ] ; then
- yes | npm i && cd app && nvm use && npm i && cd ../resfulservice && nvm use && npm i && cd .. && docker compose build
+ yes | npm i && cd app && nvm use && npm i && cd ../resfulservice && nvm use && npm i && cd .. && docker compose up
  echo "Completed '$args' successfully!"
  exit
 elif [ "$args" == "install" ] ; then
